# Generated by Django 4.2.6 on 2025-04-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dato1', models.IntegerField()),
                ('dato2', models.CharField(max_length=100)),
            ],
        ),
    ]
